server:
  port: 18888
spring:
  application:
    name: tlmall-gateway

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: tlmall-nacos-server:8848
        username: nacos
        password: nacos

    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: tlmall-sentinel-dashboard:8888

    gateway:
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        - id: user_route   #路由ID，全局唯一
          uri: lb://tlmall-user-openfeign-demo  #lb 整合负载均衡器loadbalancer
          predicates:
            - Path=/user/**   # 断言，路径相匹配的进行路由

        - id: order_route  #路由ID，全局唯一
          # 测试 http://localhost:18888/order/getOrder?userId=fox
          uri: lb://tlmall-order01  #lb 整合负载均衡器loadbalancer
          predicates:
            - Path=/order/**   # 断言，路径相匹配的进行路由
            # Header匹配  请求中带有请求头名为 x-request-id，其值与 \d+ 正则表达式匹配
            #- Header=X-Request-Id, \d+

          #配置过滤器工厂
          filters:
          #- AddRequestHeader=X-Request-color, red  #添加请求头
          #- AddRequestParameter=color, blue  # 添加请求参数
          #- CheckAuth=fox,男  #自定义过滤器工厂
      #            - name: RequestRateLimiter   #限流过滤器
      #              args:
      #                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充速率, 指的是允许用户每秒执行多少请求，不丢弃任何请求;
      #                redis-rate-limiter.burstCapacity: 2 #令牌桶的总容量, 指的是用户在一秒钟内允许执行的最大请求数，也就是令牌桶可以保存的令牌数, 如果将此值设置为零将阻止所有请求;
      #                redis-rate-limiter.requestedTokens: 1   # 指的是每个请求消耗多少个令牌, 默认是1.
      #                key-resolver: "#{@keyResolver}" # 指的是限流的时候以什么维度来判断，使用SpEL表达式按名称引用Bean



      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION

  data:
    #配置redis地址
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 200
          max-wait: 10000
          max-idle: 100
          min-idle: 10