server:
  port: 8050
spring:
  application:
    name: tlmall-user
  cloud:
    nacos:
      discovery:
        #### 1. Nacos 注册中心实验
        # 实验1.1 - 基础实验环境配置
        server-addr: tlmall-nacos-server:8848
        username: nacos
        password: nacos
        # 实验1.2 指定命名空间（用于服务逻辑隔离实验）
        # namespace: dev
        #
        # 实验1.3 指定所属集群（用于集群元数据实验）
        # cluster-name: sh-cluster
        #
        # 实验1.4 设置实例元数据（用于实例元数据实验）
        # metadata:
        #  version: "v2.1.0"
        #  region: "cn-shanghai"
        #  usage: "demo"
        #  weight: "100"
        #
        # 实验1.5 指定命名空间（用于安全配置实验）
        # namespace:fox
        #
        ### 实验1.6 指定Nacos集群地址（Nacos集群实验）
        ### 1.6.1(方案一)：直连多节点
        # 优势：无额外单点，客户端自动故障转移
        # 劣势：不便于管理配置和运维，不推荐配置IP
        # server-addr: 192.168.65.207:8848,192.168.65.208:8848,192.168.65.213:8848
        ### 1.6.2(方案二)：通过 Nginx 解耦
        # 优势：配置集中管理，便于运维
        # 劣势：引入新的单点
        # server-addr: nacos.tlmall.com:8848
        #
        ### 2. Spring Cloud LoadBalancer实验
        # 实验2.1 微服务启动阶段访问下游（方法2）
        # (1) 取消下面两行配置的注释
        # (2) 取消StartupSyncLoader和NacosManualRegistrater中的@Component注解
        # 但是并不推荐这个方法，原因有两点：
        # (1) Nacos官方并不提供“延迟注册”的功能，这是参照特定版本源码的”Walk Around“
        # (2) 这个方法只解决了启动阶段如何延迟注册，而“心跳断联”后重新注册等问题，并没有解决
        # (3) 继续打“布丁”会越打越复杂
        # (4) 所有实现都依赖Nacos Registry的特定版本的代码实现，耦合太深
        #
        # enabled: true           # 保持Nacos Discovery在启动状态
        # register-enabled: false # 关闭自动注册，等数据加载完成后，再手动注册到Nacos上
    loadbalancer:
      nacos:
        # Spring Cloud LoadBalancer 实验
        # - 为true时会开启NacosLoadBalancer
        # - 为false时根据其它配置来决定策略，缺省情况下使用RoundRobinBalancer
        enabled: false